routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});

/*-----Backend ----------*/

Route::put('categories/{category}/toggle-status', 'CategoryController@toggleStatus')->name('categories.toggleStatus');
Route::resource('categories', 'CategoryController')->except([ 'show']);

Route::resource('posts', 'PostController');

Route::resource('messages', 'MessageController');

Route::resource('subscribes', 'SubscribeController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
      'name', 'status'
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id', 'DESC')->get();
        return view('category.index')->with([
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required',
        ]);

        $category = new Category();
        $category->name = $request->name;
        $category->status = true;

        $category->save();
//        return $request;
        return redirect()->route('categories.index')->with('success', 'Create data successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('category.edit')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
        ]);

        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->save();

        return redirect()->route('categories.index')->with('success', 'Category update successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return redirect()->route('categories.index')->with('success', 'Delete Categories Successfully');
    }

    public function toggleStatus(Category $category){
        $category->status = !$category->status;
        $category->save();
        return redirect()->back()->withSuccess("Category status updated successfully!");
    }
}

resources/views/category/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card bg-light rounded-0 my-5">
        <div class="card-header">
            <span class="float-left"><strong>Category</strong>List</span>
            <span class="float-right"><a href="{{ route('categories.index') }}" class="btn btn-primary btn-sm">Create new Category</a></span>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('categories.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="name">Category Name:</label>
                    <input type="text" class="form-control" name="name"/>
                </div>

                <button type="submit" class="btn btn-primary btn-sm">Create</button>
            </form>
        </div>
    </div>



@endsection

resources/views/category/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card bg-light rounded-0 my-5">
        <div class="card-header">
            <span class="float-left"><strong>Category</strong>List</span>
            <span class="float-right"><a href="{{ route('categories.index') }}" class="btn btn-primary btn-sm">Create new Category</a></span>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('categories.update', $category->id) }}">
                <div class="form-group">
                    @csrf
                    @method('put')
                    <label for="name">Category Name:</label>
                    <input type="text" class="form-control" name="name" value="{{ $category->name }}"/>
                </div>

                <button type="submit" class="btn btn-primary btn-sm">Create</button>
            </form>
        </div>
    </div>



@endsection

resources/views/category/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card bg-light rounded-0 my-5">
        <div class="card-header">
            <span class="float-left"><strong>Category</strong>List</span>
            <span class="float-right"><a href="{{ route('categories.create') }}" class="btn btn-primary btn-sm">Create new Category</a></span>
        </div>
        <div class="card-body">
            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">SL</th>
                    <th scope="col">Name</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $k=>$category)
                <tr>
                    <th scope="row">{{ $k+1 }}</th>
                    <td>{{ $category->name }}</td>
                    <td>
                        <form method="post" action="{{ route('categories.toggleStatus', $category->id) }}">
                            @csrf
                            @method('PUT')
                            <button href type="submit" class="btn {{ $category->status ? "btn-success" : "btn-danger" }} btn-sm">{{ $category->status ? "Published" : "Unpublished" }}</button>
                        </form>
                    </td>
                    <td>
                        <form method="post" action="{{ route('categories.destroy', $category->id) }}" >
                            @csrf
                            @method('DELETE')
                            <a class="btn btn-primary btn-sm" href="{{ route('categories.edit', $category->id) }}">Edit</a>
                            <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>



@endsection