routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});

/*-----Backend ----------*/

Route::put('categories/{category}/toggle-status', 'CategoryController@toggleStatus')->name('categories.toggleStatus');
Route::resource('categories', 'CategoryController')->except([ 'show']);

Route::resource('posts', 'PostController');

Route::resource('messages', 'MessageController');

Route::resource('subscribes', 'SubscribeController');

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    public $table = 'messages';
    protected $fillable = [
        'name',
        'email',
        'website',
        'subject',
        'message',
        'status'
    ];

}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Message;
use Illuminate\Http\Request;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $messages = Message::orderBy('id', 'DESC')->get();
        return view('message.index')->with([
            'messages' => $messages
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'message' => 'required'
        ]);
//        dd($request->all());
        Message::create($request->all());
        return back()->with('success', 'Thanks for contacting us!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $message = Message::findOrFail($id);
        return view('message.show')->with([
            'message' => $message
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/message/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card bg-light rounded-0 my-5">
        <div class="card-header">
            <span class="float-left"><strong>Category</strong>List</span>
            <span class="float-right"><a href="{{ route('categories.index') }}" class="btn btn-primary btn-sm">Create new Category</a></span>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('categories.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="name">Category Name:</label>
                    <input type="text" class="form-control" name="name"/>
                </div>

                <button type="submit" class="btn btn-primary btn-sm">Create</button>
            </form>
        </div>
    </div>



@endsection

resources/views/message/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card bg-light rounded-0 my-5">
        <div class="card-header">
            <span class="float-left"><strong>Category</strong>List</span>
            <span class="float-right"><a href="{{ route('categories.index') }}" class="btn btn-primary btn-sm">Create new Category</a></span>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('categories.update', $category->id) }}">
                <div class="form-group">
                    @csrf
                    @method('put')
                    <label for="name">Category Name:</label>
                    <input type="text" class="form-control" name="name" value="{{ $category->name }}"/>
                </div>

                <button type="submit" class="btn btn-primary btn-sm">Create</button>
            </form>
        </div>
    </div>



@endsection

resources/views/message/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card bg-light rounded-0 my-5">
        <div class="card-header">
            <span class="float-left"><strong>Messages</strong>List</span>
{{--            <span class="float-right"><a href="{{ route('categories.create') }}" class="btn btn-primary btn-sm">Create new Category</a></span>--}}
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">SL</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Text</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($messages as $k=>$message)
                <tr>
                    <th scope="row">{{ $k+1 }}</th>
                    <td>{{ $message->name }}</td>
                    <td>{{ $message->email }}</td>
                    <td>{{ $message->subject }}</td>
                    <td>{{ $message->website }}</td>
                    <td>{{ $message->text }}</td>
                    <td>
                        <a href="{{ route('messages.show', $message->id) }}" class="btn btn-sm btn-primary">Vew</a>
                    </td>
                </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>



@endsection

resources/views/message/show.blade.php
@extends('layouts.admin')

@section('content')

    <div class="card bg-light rounded-0 my-5">
        <div class="card-header">
            <span class="float-left"><strong>Messages</strong>List</span>
            <span class="float-right"><a href="{{ route('messages.index') }}" class="btn btn-primary btn-sm">Go To Messages List</a></span>
        </div>
        <div class="card-body">
                <p><Strong>Name : </Strong>{{ $message->name }}</p>
                <p><Strong>Email : </Strong>{{ $message->email }}</p>
                <p><Strong>Website : </Strong>{{ $message->website ?? "" }}</p>
                <p><Strong>Subject : </Strong>{{ $message->subject ?? "" }}</p>
                <p><Strong>Message : </Strong>{{ $message->message }}</p>
        </div>
    </div>



@endsection